export interface Building {
    type: string;
    name: string;
    fullName: string;
    simpleName: string[];
}

export const BuildingList: Building[] = [
    {
        type: "教学楼",
        name: "第六教学楼",
        fullName: "广西大学东校园第六教学楼",
        simpleName: ["六教", "6A", "6B", "六一阶", "六二阶"],
    },
    {
        type: "教学楼",
        name: "第十教学楼",
        fullName: "广西大学东校园第十教学楼",
        simpleName: ["十教"],
    },
    {
        type: "教学楼",
        name: "西校园综合楼",
        fullName: "广西大学西校园综合实验大楼",
        simpleName: ["西综合"],
    },
    {
        type: "学院",
        name: "计算机与电子信息学院",
        fullName: "广西大学西校园计算机与电子信息学院",
        simpleName: ["计电学院"],
    },
    {
        type: "学院",
        name: "机械工程学院",
        fullName: "广西大学西校园机械工程学院",
        simpleName: ["机械学院"],
    },
    {
        type: "学院",
        name: "电气工程学院",
        fullName: "广西大学西校园电气工程学院",
        simpleName: ["电气学院"],
    },
    {
        type: "学院",
        name: "土木建筑工程学院",
        fullName: "广西大学西校园土木建筑工程学院",
        simpleName: ["土木学院"],
    },
    {
        type: "学院",
        name: "化学化工学院",
        fullName: "广西大学西校园化学化工学院",
        simpleName: ["化学院"],
    },
    {
        type: "学院",
        name: "资源环境与材料学院",
        fullName: "广西大学西校园资源环境与材料学院",
        simpleName: ["资环材学院"],
    },
    {
        type: "学院",
        name: "轻工与食品工程学院",
        fullName: "广西大学西校园轻工与食品工程学院",
        simpleName: ["轻工食品学院"],
    },
    {
        type: "学院",
        name: "海洋学院",
        fullName: "广西大学海洋学院",
        simpleName: ["海洋学院"],
    },
    {
        type: "学院",
        name: "生命科学与技术学院",
        fullName: "广西大学东校园生命科学与技术学院",
        simpleName: ["生科学院"],
    },
    {
        type: "学院",
        name: "农学院",
        fullName: "广西大学东校园农学院",
        simpleName: ["农学院"],
    },
    {
        type: "学院",
        name: "动物科学技术学院",
        fullName: "广西大学东校园动物科学技术学院",
        simpleName: ["动科学院"],
    },
    {
        type: "学院",
        name: "林学院",
        fullName: "广西大学东校园林学院",
        simpleName: ["林学院"],
    },
    {
        type: "学院",
        name: "数学与信息科学学院",
        fullName: "广西大学西校园数学与信息科学学院",
        simpleName: ["数信学院"],
    },
    {
        type: "学院",
        name: "物理科学与工程技术学院",
        fullName: "广西大学西校园物理科学与工程技术学院",
        simpleName: ["物理学院"],
    },
    {
        type: "学院",
        name: "文学院",
        fullName: "广西大学西校园文学院",
        simpleName: ["文学院"],
    },
    {
        type: "学院",
        name: "新闻与传播学院",
        fullName: "广西大学新闻传播学院",
        simpleName: ["新传学院"],
    },
    {
        type: "学院",
        name: "外国语学院",
        fullName: "广西大学西校园外国语学院",
        simpleName: ["外语学院"],
    },
    {
        type: "学院",
        name: "艺术学院",
        fullName: "广西大学东校园艺术学院",
        simpleName: ["艺术学院"],
    },
    {
        type: "学院",
        name: "公共管理学院",
        fullName: "广西大学西校园公共管理学院",
        simpleName: ["公管学院"],
    },
    {
        type: "学院",
        name: "工商管理学院",
        fullName: "广西大学西校园工商管理学院",
        simpleName: ["工商学院"],
    },
    {
        type: "学院",
        name: "法学院",
        fullName: "广西大学西校园法学院",
        simpleName: ["法学院"],
    },
    {
        type: "学院",
        name: "马克思主义学院",
        fullName: "广西大学西校园马克思主义学院",
        simpleName: ["马院"],
    },
    {
        type: "学院",
        name: "体育学院",
        fullName: "广西大学西校园体育学院",
        simpleName: ["体育学院"],
    },
    {
        type: "学院",
        name: "医学院",
        fullName: "广西大学医学院",
        simpleName: ["医学院"],
    },
    {
        type: "学院",
        name: "继续教育学院",
        fullName: "广西大学新东园继续教育学院",
        simpleName: ["继教学院"],
    },
    {
        type: "学院",
        name: "中国—东盟经济学院／经济学院／中国—东盟金融合作学院",
        fullName: "广西大学中国-东盟经济学院",
        simpleName: ["东盟学院", "经济学院", "金融学院"],
    },
    {
        type: "食堂",
        name: "南苑食堂",
        fullName: "广西大学西校园南苑餐厅",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "北苑食堂",
        fullName: "广西大学北苑餐厅",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "东苑食堂",
        fullName: "广西大学东校园东苑餐厅",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "萃苑食堂",
        fullName: "广西大学西校园萃苑餐厅",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "秀苑食堂",
        fullName: "广西大学新东园秀苑餐厅",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "荟萃楼",
        fullName: "广西大学西校园荟萃楼",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "博萃楼",
        fullName: "广西大学西校园博萃楼",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "东27供餐点",
        fullName: "广西大学东校园学生公寓东27栋(装修中)",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "西22供餐点",
        fullName: "广西大学西校园学生宿舍22栋",
        simpleName: [],
    },
    {
        type: "食堂",
        name: "KFC",
        fullName: "广西大学东校园大学生活动中心",
        simpleName: [],
    },
    {
        type: "大门",
        name: "南门",
        fullName: "广西大学(南门)",
        simpleName: [],
    },
    {
        type: "大门",
        name: "东门",
        fullName: "广西大学(东门)",
        simpleName: [],
    },
    {
        type: "大门",
        name: "西门",
        fullName: "广西大学(西门)",
        simpleName: [],
    },
    {
        type: "大门",
        name: "西南门",
        fullName: "广西大学(西南门)",
        simpleName: [],
    },
    {
        type: "大门",
        name: "北门",
        fullName: "广西大学西校园(北门)",
        simpleName: [],
    },
    {
        type: "大门",
        name: "东高门",
        fullName: "广西大学(东高门)",
        simpleName: [],
    },
];
