export interface IPos {
    type: "教学楼" | "学院" | "食堂" | "校门" | "综合性建筑" | "体育场" | "店铺" | "宿舍" | "其他";
    test: RegExp | ((text: string) => boolean);
    name: string;
    fullName: string;
    simpleName: string[];
}

export const BuildingList: IPos[] = [
    {
        type: "教学楼",
        name: "东校园第六教学楼",
        fullName: "广西大学东校园第六教学楼",
        simpleName: ["六教", "6A", "6B", "六一阶", "六二阶"],
        test: /^(6[AB]|六[一二]阶)/,
    },
    {
        type: "教学楼",
        name: "东校园第十教学楼",
        fullName: "广西大学东校园第十教学楼",
        simpleName: ["十教", "东10-A", "东10-B"],
        test: /^东10/,
    },
    {
        type: "教学楼",
        name: "西校园第二教学楼",
        fullName: "广西大学西校园第二教学楼",
        simpleName: ["二教", "西二"],
        test: /^西2/,
    },
    {
        type: "教学楼",
        name: "西校园第三教学楼",
        fullName: "广西大学西校园第三教学楼",
        simpleName: ["三教", "西三"],
        test: /^西3/,
    },
    {
        type: "教学楼",
        name: "西校园第四教学楼",
        fullName: "广西大学西校园第四教学楼",
        simpleName: ["四教", "西四"],
        test: /^西4/,
    },
    {
        type: "综合性建筑",
        name: "西校园大礼堂",
        fullName: "广西大学西校园大礼堂",
        simpleName: ["大礼堂"],
        test: /大礼堂/,
    },
    {
        type: "综合性建筑",
        name: "西校园汇学堂",
        fullName: "广西大学西校园汇学堂",
        simpleName: ["汇学堂"],
        test: /汇学堂/,
    },
    {
        type: "综合性建筑",
        name: "东校园图书馆",
        fullName: "广西大学东校园图书馆",
        simpleName: ["图书馆"],
        test: /图书馆|^图/,
    },
    {
        type: "综合性建筑",
        name: "行健图书馆",
        fullName: "广西大学图书馆行健馆",
        simpleName: ["图书馆"],
        test: /#/,
    },
    {
        type: "综合性建筑",
        name: "西校园综合楼",
        fullName: "广西大学西校园综合实验大楼",
        simpleName: ["西综合"],
        test: /西综合|综合楼/,
    },
    {
        type: "学院",
        name: "计算机与电子信息学院",
        fullName: "广西大学西校园计算机与电子信息学院",
        simpleName: ["计电学院"],
        test: /^计电/,
    },
    {
        type: "学院",
        name: "机械工程学院",
        fullName: "广西大学西校园机械工程学院",
        simpleName: ["机械学院"],
        test: /机械/,
    },
    {
        type: "学院",
        name: "电气工程学院",
        fullName: "广西大学西校园电气工程学院",
        simpleName: ["电气学院"],
        test: /电气/,
    },
    {
        type: "学院",
        name: "土木建筑工程学院",
        fullName: "广西大学西校园土木建筑工程学院",
        simpleName: ["土木学院"],
        test: /^土/,
    },
    {
        type: "学院",
        name: "化学化工学院",
        fullName: "广西大学西校园化学化工学院",
        simpleName: ["化学院"],
        test: /^化/,
    },
    {
        type: "学院",
        name: "资源环境与材料学院",
        fullName: "广西大学西校园资源环境与材料学院",
        simpleName: ["资环材学院"],
        test: /资环材|资源环境与材料/,
    },
    {
        type: "学院",
        name: "轻工与食品工程学院",
        fullName: "广西大学西校园轻工与食品工程学院",
        simpleName: ["轻工食品学院"],
        test: /轻工/,
    },
    {
        type: "学院",
        name: "海洋学院",
        fullName: "广西大学海洋学院",
        simpleName: ["海洋学院"],
        test: /海洋/,
    },
    {
        type: "学院",
        name: "生命科学与技术学院",
        fullName: "广西大学东校园生命科学与技术学院",
        simpleName: ["生科学院"],
        test: /生科|生命科学/,
    },
    {
        type: "学院",
        name: "农学院",
        fullName: "广西大学东校园农学院",
        simpleName: ["农学院"],
        test: /农/,
    },
    {
        type: "学院",
        name: "动物科学技术学院",
        fullName: "广西大学东校园动物科学技术学院",
        simpleName: ["动科学院"],
        test: /^动/,
    },
    {
        type: "学院",
        name: "林学院",
        fullName: "广西大学东校园林学院",
        simpleName: ["林学院"],
        test: /^林/,
    },
    {
        type: "学院",
        name: "数学与信息科学学院",
        fullName: "广西大学西校园数学与信息科学学院",
        simpleName: ["数信学院"],
        test: /数信|数学与信息/,
    },
    {
        type: "学院",
        name: "物理科学与工程技术学院",
        fullName: "广西大学西校园物理科学与工程技术学院",
        simpleName: ["物理学院"],
        test: /物理/,
    },
    {
        type: "学院",
        name: "文学院",
        fullName: "广西大学西校园文学院",
        simpleName: ["文学院"],
        test: /^文/,
    },
    {
        type: "学院",
        name: "新闻与传播学院",
        fullName: "广西大学新闻传播学院",
        simpleName: ["新传学院"],
        test: /新闻/,
    },
    {
        type: "学院",
        name: "外国语学院",
        fullName: "广西大学西校园外国语学院",
        simpleName: ["外语学院"],
        test: /外语/,
    },
    {
        type: "学院",
        name: "艺术学院",
        fullName: "广西大学东校园艺术学院",
        simpleName: ["艺术学院"],
        test: /艺术/,
    },
    {
        type: "学院",
        name: "公共管理学院",
        fullName: "广西大学西校园公共管理学院",
        simpleName: ["公管学院"],
        test: /公管|公共管理/,
    },
    {
        type: "学院",
        name: "工商管理学院",
        fullName: "广西大学西校园工商管理学院",
        simpleName: ["工商学院"],
        test: /工商|^商/,
    },
    {
        type: "学院",
        name: "法学院",
        fullName: "广西大学西校园法学院",
        simpleName: ["法学院"],
        test: /^法/,
    },
    {
        type: "学院",
        name: "马克思主义学院",
        fullName: "广西大学西校园马克思主义学院",
        simpleName: ["马院"],
        test: /^马/,
    },
    {
        type: "学院",
        name: "体育学院",
        fullName: "广西大学西校园体育学院",
        simpleName: ["体育学院"],
        test: /^体育/,
    },
    {
        type: "学院",
        name: "医学院",
        fullName: "广西大学医学院",
        simpleName: ["医学院"],
        test: /^医/,
    },
    {
        type: "学院",
        name: "继续教育学院",
        fullName: "广西大学新东园继续教育学院",
        simpleName: ["继教学院"],
        test: /^继教/,
    },
    {
        type: "学院",
        name: "中国—东盟经济学院／经济学院／中国—东盟金融合作学院",
        fullName: "广西大学中国-东盟经济学院",
        simpleName: ["东盟学院", "经济学院", "金融学院"],
        test: /东盟/,
    },
    {
        type: "食堂",
        name: "南苑食堂",
        fullName: "广西大学西校园南苑餐厅",
        simpleName: [],
        test: /南苑/,
    },
    {
        type: "食堂",
        name: "北苑食堂",
        fullName: "广西大学北苑餐厅",
        simpleName: [],
        test: /北苑/,
    },
    {
        type: "食堂",
        name: "东苑食堂",
        fullName: "广西大学东校园东苑餐厅",
        simpleName: [],
        test: /东苑/,
    },
    {
        type: "食堂",
        name: "萃苑食堂",
        fullName: "广西大学西校园萃苑餐厅",
        simpleName: [],
        test: /萃苑/,
    },
    {
        type: "食堂",
        name: "秀苑食堂",
        fullName: "广西大学新东园秀苑餐厅",
        simpleName: [],
        test: /秀苑/,
    },
    {
        type: "食堂",
        name: "荟萃楼",
        fullName: "广西大学西校园荟萃楼",
        simpleName: [],
        test: /荟萃/,
    },
    {
        type: "食堂",
        name: "博萃楼",
        fullName: "广西大学西校园博萃楼",
        simpleName: [],
        test: /博萃/,
    },
    {
        type: "食堂",
        name: "东27供餐点",
        fullName: "广西大学东校园学生公寓东27栋(装修中)",
        simpleName: [],
        test: /#/,
    },
    {
        type: "食堂",
        name: "西22供餐点",
        fullName: "广西大学西校园学生宿舍22栋",
        simpleName: [],
        test: /#/,
    },
    {
        type: "食堂",
        name: "KFC、老水塔咖啡",
        fullName: "广西大学东校园大学生活动中心",
        simpleName: [],
        test: /#/,
    },
    {
        type: "校门",
        name: "南门",
        fullName: "广西大学(南门)",
        simpleName: ["西综合楼南侧"],
        test: /#/,
    },
    {
        type: "校门",
        name: "中南门",
        fullName: "广西大学西校园(北门)",
        simpleName: ["西大附中对面"],
        test: /#/,
    },
    {
        type: "校门",
        name: "东门",
        fullName: "广西大学(东门)",
        simpleName: ["东体育场旁"],
        test: /#/,
    },
    {
        type: "校门",
        name: "西门",
        fullName: "广西大学(西门)",
        simpleName: ["西菜市场旁"],
        test: /#/,
    },
    {
        type: "校门",
        name: "南侧门",
        fullName: "广西大学(西南门)",
        simpleName: ["公共管理学院旁"],
        test: /#/,
    },
    {
        type: "校门",
        name: "新东门",
        fullName: "广西大学(新东门)",
        simpleName: ["科研院旁"],
        test: /#/,
    },
    {
        type: "校门",
        name: "东高门",
        fullName: "广西大学(东高门)",
        simpleName: ["教职工集资楼旁"],
        test: /#/,
    },
    {
        type: "校门",
        name: "秀厢北门",
        fullName: "广西大学行健文理学院(北区东门)",
        simpleName: ["行健图书馆旁"],
        test: /#/,
    },
    {
        type: "校门",
        name: "北西门",
        fullName: "广西大学北校园(西门)",
        simpleName: ["东33栋旁"],
        test: /#/,
    },
    {type: "宿舍", name: "西1栋", fullName: "广西大学西校园学生宿舍1栋", simpleName: [], test: /#/},
    {
        type: "宿舍",
        name: "西2栋",
        fullName: "广西大学西校园学生宿舍2栋",
        simpleName: [],
        test: /#/,
    },
    {
        type: "宿舍",
        name: "西3栋",
        fullName: "广西大学西校园学生宿舍3栋",
        simpleName: [],
        test: /#/,
    },
    {
        type: "宿舍",
        name: "西4栋",
        fullName: "广西大学西校园学生宿舍4栋",
        simpleName: [],
        test: /#/,
    },
    {
        type: "宿舍",
        name: "西5栋",
        fullName: "广西大学西校园学生宿舍5栋",
        simpleName: [],
        test: /#/,
    },
    {type: "宿舍", name: "西5栋", fullName: "广西大学西校园学生宿舍5栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西6B栋", fullName: "广西大学西校园学生宿舍6B栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西7栋", fullName: "广西大学西校园学生宿舍7栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西8栋", fullName: "广西大学西校园学生宿舍8栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西9栋", fullName: "广西大学西校园学生宿舍9栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西10栋", fullName: "广西大学西校园学生宿舍10栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西11栋", fullName: "广西大学西校园学生宿舍11栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西12栋", fullName: "广西大学西校园学生宿舍12栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西13栋", fullName: "广西大学西校园研究生宿舍区13栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西14栋", fullName: "广西大学新东园西校园学生宿舍14栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西15栋", fullName: "广西大学西校园学生宿舍15栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西17栋", fullName: "广西大学西校园学生宿舍17栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西18栋", fullName: "广西大学西校园学生宿舍18栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西19栋", fullName: "广西大学西校园学生宿舍19栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西20栋", fullName: "广西大学西校园学生宿舍20栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西21栋", fullName: "广西大学西校园学生宿舍21栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西22栋", fullName: "广西大学西校园学生宿舍22栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西23栋", fullName: "广西大学西校园学生宿舍23栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西24栋", fullName: "广西大学西校园学生宿舍24栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西25栋", fullName: "广西大学西校园学生宿舍25栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西26栋", fullName: "广西大学西校园学生宿舍26栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西27栋", fullName: "广西大学西校园学生宿舍27栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "西28栋", fullName: "广西大学西校园学生宿舍28栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东1栋", fullName: "广西大学东校园东区1栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东1A、B栋", fullName: "广西大学东校园学生宿舍1栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东2栋", fullName: "广西大学东校园学生宿舍2栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东3栋", fullName: "广西大学东校园学生宿舍3栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东4栋", fullName: "广西大学东校园学生宿舍4栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东5栋", fullName: "广西大学东校园学生宿舍5栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东6栋", fullName: "广西大学东校园学生宿舍6栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东7栋", fullName: "广西大学东校园学生公寓7栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东8栋", fullName: "广西大学东校园学生宿舍8栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东9栋", fullName: "广西大学东校园学生宿舍9栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东10栋", fullName: "广西大学东校园学生宿舍10栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东11栋", fullName: "广西大学东校园学生宿舍11栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东12栋", fullName: "广西大学东校园学生宿舍12栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东13栋", fullName: "广西大学东校园学生宿舍13栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东14栋", fullName: "广西大学东校园学生宿舍14栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东16栋", fullName: "广西大学东校园留学生公寓", simpleName: [], test: /#/},
    {type: "宿舍", name: "东17栋", fullName: "广西大学东校园学生公寓17栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东18栋", fullName: "广西大学东校园学生公寓东18栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东19栋", fullName: "广西大学新东园学生公寓东19栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东20栋", fullName: "广西大学新东园学生公寓东20栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东21栋", fullName: "广西大学新东园学生公寓东21栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东22栋", fullName: "广西大学新东园学生公寓东22栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东23栋", fullName: "广西大学新东园学生公寓东23栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东25栋", fullName: "广西大学新东园秀园校区(南门)25号楼", simpleName: [], test: /#/},
    {type: "宿舍", name: "东27栋", fullName: "广西大学东校园学生公寓东27栋(装修中)", simpleName: [], test: /#/},
    {type: "宿舍", name: "东28栋", fullName: "广西大学东校园青年教师公寓东28栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东29栋", fullName: "广西大学学生宿舍东29栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东30栋", fullName: "广西大学行健文理学院学生宿舍2栋A座", simpleName: [], test: /#/},
    {type: "宿舍", name: "东31栋", fullName: "广西大学行健文理学院学生宿舍3栋B座", simpleName: [], test: /#/},
    {type: "宿舍", name: "东32栋", fullName: "广西大学行健文理学院学生宿舍3栋B座", simpleName: [], test: /#/},
    {type: "宿舍", name: "东33栋", fullName: "广西大学行健文理学院学生宿舍5栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东34栋", fullName: "广西大学东34栋", simpleName: [], test: /#/},
    {type: "宿舍", name: "东35栋", fullName: "广西大学东校园学生宿舍35栋", simpleName: [], test: /#/},
];
